In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [3]:
import numpy as np

In [4]:
from tree_modules.tree_base import MyTree
from tree_modules.random_forest import MyForest

## データの読み込み

In [5]:
iris = datasets.load_iris()

In [6]:
X = iris.data
y = iris.target

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [8]:
X_train.shape, y_train.shape

((112, 4), (112,))

In [9]:
X_test.shape, y_test.shape

((38, 4), (38,))

## 決定木を試す

In [10]:
tree = MyTree()

In [11]:
tree.fit(X_train, y_train)

In [12]:
y_pred = tree.predict(X_test)

In [13]:
y_pred

array([2, 0, 0, 1, 2, 1, 2, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 2, 0, 1,
       2, 1, 1, 2, 1, 0, 2, 0, 1, 2, 1, 0, 2, 2, 1, 2])

In [14]:
y_test

array([1, 0, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 2, 0, 1,
       2, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 0, 2, 2, 1, 1])

In [15]:
(y_pred == y_test).sum() / len(y_test)

0.8947368421052632

## ランダムフォレストを試す

In [53]:
myrf = MyForest(n_estimators=100)

In [54]:
myrf.fit(X_train, y_train)

In [55]:
y_pred = myrf.predict(X_test)

In [56]:
y_pred

array([1, 0, 0, 1, 2, 1, 2, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 2, 0, 1,
       2, 1, 1, 2, 1, 0, 2, 0, 1, 2, 1, 0, 2, 2, 1, 1])

In [57]:
y_test

array([1, 0, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 2, 0, 1,
       2, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 0, 2, 2, 1, 1])

In [58]:
(y_pred == y_test).sum() / len(y_test)

0.9473684210526315

In [59]:
myrf.predict_proba(X_test)

array([[0.  , 0.5 , 0.5 ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.38, 0.62],
       [0.  , 1.  , 0.  ],
       [0.  , 0.01, 0.99],
       [0.  , 0.99, 0.01],
       [1.  , 0.  , 0.  ],
       [0.  , 0.98, 0.02],
       [1.  , 0.  , 0.  ],
       [0.  , 0.84, 0.16],
       [0.  , 1.  , 0.  ],
       [0.01, 0.04, 0.95],
       [0.  , 0.13, 0.87],
       [0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.97, 0.03, 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.01, 0.99],
       [0.  , 1.  , 0.  ],
       [0.  , 0.94, 0.06],
       [0.  , 0.08, 0.92],
       [0.  , 0.75, 0.25],
       [0.99, 0.01, 0.  ],
       [0.  , 0.15, 0.85],
       [0.99, 0.01, 0.  ],
       [0.  , 0.95, 0.05],
       [0.  , 0.  , 1.  ],
       [0.  , 0.91, 0.09],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
 

In [60]:
myrf.n_classes

3