In [2]:
%load_ext autoreload
%autoreload 2

In [9]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [4]:
import numpy as np

In [7]:
from tree_modules.tree_base import MyTree
from tree_modules.random_forest import MyForest

## データの読み込み

In [5]:
iris = datasets.load_iris()

In [6]:
X = iris.data
y = iris.target

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [159]:
X_train.shape, y_train.shape

((112, 4), (112,))

In [160]:
X_test.shape, y_test.shape

((38, 4), (38,))

## 決定木を試す

In [12]:
tree = MyTree()

In [13]:
tree.fit(X_train, y_train)

In [14]:
y_pred = tree.predict(X_test)

In [15]:
y_pred

array([2, 1, 0, 1, 0, 1, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 1, 2, 2, 0, 1,
       2, 1, 0, 2, 1, 2, 1, 0, 0, 2, 2, 2, 0, 2, 1, 2])

In [16]:
y_test

array([2, 1, 0, 1, 0, 1, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1,
       2, 1, 0, 2, 1, 2, 1, 0, 0, 2, 2, 2, 0, 2, 1, 2])

In [17]:
(y_pred == y_test).sum() / len(y_test)

0.9736842105263158

## ランダムフォレストを試す

In [18]:
myrf = MyForest(n_estimators=100)

In [19]:
myrf.fit(X_train, y_train)

In [20]:
y_pred = myrf.predict(X_test)

In [21]:
y_pred

array([2, 1, 0, 1, 0, 1, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 1, 2, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 1, 0, 0, 2, 2, 2, 0, 2, 1, 2])

In [22]:
y_test

array([2, 1, 0, 1, 0, 1, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1,
       2, 1, 0, 2, 1, 2, 1, 0, 0, 2, 2, 2, 0, 2, 1, 2])

In [23]:
(y_pred == y_test).sum() / len(y_test)

0.9473684210526315

In [24]:
myrf.predict_proba(X_test)

array([[0.  , 0.01, 0.99],
       [0.  , 0.98, 0.02],
       [1.  , 0.  , 0.  ],
       [0.  , 0.77, 0.23],
       [1.  , 0.  , 0.  ],
       [0.  , 0.99, 0.01],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 0.92, 0.08],
       [0.  , 0.19, 0.81],
       [0.  , 0.2 , 0.8 ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.96, 0.04],
       [0.  , 0.  , 1.  ],
       [0.  , 0.96, 0.04],
       [1.  , 0.  , 0.  ],
       [0.  , 0.96, 0.04],
       [0.  , 0.  , 1.  ],
       [0.  , 0.  , 1.  ],
       [0.98, 0.02, 0.  ],
       [0.  , 0.98, 0.02],
       [0.  , 0.5 , 0.5 ],
       [0.  , 0.99, 0.01],
       [0.83, 0.17, 0.  ],
       [0.  , 0.03, 0.97],
       [0.  , 0.98, 0.02],
       [0.  , 0.  , 1.  ],
       [0.  , 0.93, 0.07],
       [0.91, 0.09, 0.  ],
       [0.89, 0.11, 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 0.01, 0.99],
       [0.  , 0.01, 0.99],
       [1.  , 0.  , 0.  ],
       [0.  , 0.01, 0.99],
       [0.  , 0.99, 0.01],
 

In [25]:
myrf.n_classes

3