In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [3]:
import numpy as np

In [4]:
from tree_modules.tree_base import MyTree
from tree_modules.random_forest import MyForest

## データの読み込み

In [5]:
iris = datasets.load_iris()

In [6]:
X = iris.data
y = iris.target

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [8]:
X_train.shape, y_train.shape

((112, 4), (112,))

In [9]:
X_test.shape, y_test.shape

((38, 4), (38,))

## 決定木を試す

In [10]:
tree = MyTree(max_depth=2)

In [11]:
tree.fit(X_train, y_train)

In [12]:
y_pred = tree.predict(X_test)

In [13]:
y_pred

array([0, 0, 2, 0, 2, 0, 2, 0, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 2, 0, 2, 1,
       2, 2, 1, 0, 2, 1, 2, 2, 2, 2, 0, 2, 0, 1, 1, 2])

In [14]:
y_test

array([0, 0, 2, 0, 1, 0, 2, 0, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 2, 0, 2, 1,
       2, 2, 1, 0, 2, 1, 2, 2, 2, 1, 0, 1, 0, 2, 1, 2])

In [15]:
(y_pred == y_test).sum() / len(y_test)

0.8947368421052632

## ランダムフォレストを試す

In [16]:
myrf = MyForest(n_estimators=1000, max_depth=2, max_features=2)

In [17]:
myrf.fit(X_train, y_train)

In [18]:
y_pred = myrf.predict(X_test)

In [19]:
y_pred

array([0, 0, 2, 0, 2, 0, 2, 0, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 2, 0, 2, 1,
       2, 2, 1, 0, 2, 1, 2, 2, 2, 2, 0, 2, 0, 1, 1, 2])

In [20]:
y_test

array([0, 0, 2, 0, 1, 0, 2, 0, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 2, 0, 2, 1,
       2, 2, 1, 0, 2, 1, 2, 2, 2, 1, 0, 1, 0, 2, 1, 2])

In [21]:
(y_pred == y_test).sum() / len(y_test)

0.8947368421052632

In [22]:
myrf.n_classes

3

In [23]:
myrf.predict_proba(X_test)

array([[1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.011, 0.989],
       [0.865, 0.135, 0.   ],
       [0.002, 0.141, 0.857],
       [1.   , 0.   , 0.   ],
       [0.   , 0.201, 0.799],
       [0.828, 0.161, 0.011],
       [0.   , 0.997, 0.003],
       [0.   , 0.013, 0.987],
       [0.   , 0.951, 0.049],
       [0.969, 0.031, 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.002, 0.048, 0.95 ],
       [0.   , 0.   , 1.   ],
       [0.   , 0.885, 0.115],
       [1.   , 0.   , 0.   ],
       [0.   , 0.001, 0.999],
       [0.997, 0.003, 0.   ],
       [0.   , 0.088, 0.912],
       [0.005, 0.786, 0.209],
       [0.   , 0.142, 0.858],
       [0.   , 0.003, 0.997],
       [0.   , 0.951, 0.049],
       [0.999, 0.001, 0.   ],
       [0.   , 0.163, 0.837],
       [0.005, 0.813, 0.182],
       [0.   , 0.001, 0.999],
       [0.   , 0.015, 0.985],
       [0.   , 0.013, 0.987],
       [0.   , 0.462, 0.538],
       [0.829, 0.17 , 0.001],
       [0.